DROP TABLE MYTEST PURGE;

CREATE TABLE MYTEST(
NO NUMBER PRIMARY KEY,
NAME VARCHAR2(100),
NICKNAME VARCHAR2(200)
);

SELECT * FROM MYTEST;

DELETE FROM MYTEST WHERE NO = 100;

INSERT INTO MYTEST VALUES(100, '홍길동','율도');
INSERT INTO MYTEST VALUES(101, '이순신', '불멸');

DROP TABLE TB_MEMBER;

CREATE TABLE TB_MEMBER(
NO NUMBER PRIMARY KEY,
NAME VARCHAR2(100) NOT NULL,
AGE NUMBER NOT NULL,
GENDER VARCHAR2(2) CHECK(GENDER IN ('M','F')) NOT NULL,
LOCATION VARCHAR2(500),
JOB VARCHAR2(300),
TEL VARCHAR2(20),
EMAIL VARCHAR2(100)
);