DROP TABLE SCORE;

CREATE TABLE TB_MEMBER(
NO NUMBER PRIMARY KEY,
NAME VARCHAR2(100) NOT NULL,
AGE NUMBER NOT NULL,
GENDER VARCHAR2(2) CHECK(GENDER IN ('M','F')) NOT NULL,
LOCATION VARCHAR2(500),
JOB VARCHAR2(300),
TEL VARCHAR2(20),
EMAIL VARCHAR2(100)
);

SELECT NO, NAME, KOR, ENG, MATH, SUM(KOR+ENG+MATH), AVG((KOR+ENG+MATH)/3)
FROM SCORE;

INSERT INTO TB_MEMBER
VALUES(1, '강사', 100, 'M', '서울시 강남구', '선생님', '010-1224-5678', 'TEACHER@NAVER.COM');

SELECT NO, NAME, AGE, GENDER, LOCATION, JOB, TEL, EMAIL
FROM TB_MEMBER;

CREATE TABLE SCORE(
NO NUMBER PRIMARY KEY,
NAME VARCHAR2(100) NOT NULL,
KOR NUMBER,
ENG NUMBER,
MATH NUMBER,
SUM NUMBER,
AVG NUMBER
);

INSERT INTO SCORE
VALUES(3, '강감찬', 90, 80,60, NULL, NULL);

UPDATE SCORE SET MATH = 90 WHERE NO = 2;